export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';
export const INCREMENT_NOTIFICATION_COUNT = 'INCREMENT_NOTIFICATION_COUNT';
export const GET_ACTIVE_NOTIFICATION_COUNT = 'GET_ACTIVE_NOTIFICATION_COUNT';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const CLEAR_ALL_NOTIFICATIONS = 'CLEAR_ALL_NOTIFICATIONS';
export const DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

export const ADD_FLASH_NOTIFICATION = 'ADD_FLASH_NOTIFICATION';
export const REMOVE_FLASH_NOTIFICATION = 'REMOVE_FLASH_NOTIFICATION';
