export const FETCH_SCORING_CATEGORIES = 'FETCH_SCORING_CATEGORIES';

export const FETCH_THREAD_VOTES = 'FETCH_THREAD_VOTES';
export const FETCH_MESSAGE_VOTES = 'FETCH_MESSAGE_VOTES';
export const FETCH_USER_VOTE = 'FETCH_USER_VOTE';

export const SET_SCORING_CATEGORIES = 'SET_SCORING_CATEGORIES';

export const SET_THREAD_VOTES = 'SET_THREAD_VOTES';
export const SET_MESSAGE_VOTES = 'SET_MESSAGE_VOTES';
export const SET_USER_VOTE = 'SET_USER_VOTE';

export const SCORING_FORM_SUBMIT = 'SCORING_FORM_SUBMIT';
