export const ROUTE_CHANGE_START = 'ROUTE_CHANGE_START';
export const ROUTE_CHANGE_COMPLETE = 'ROUTE_CHANGE_COMPLETE';

export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';
export const RESET_FLASH_MESSAGE = 'RESET_FLASH_MESSAGE';

export const CHANGE_IS_PAGE_LOADING = 'CHANGE_IS_PAGE_LOADING';
export const ADD_LOADING_ERROR = 'ADD_LOADING_ERROR';

export const CHECK_STORAGE_VALUES = 'CHECK_STORAGE_VALUES';

export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
