export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_REFRESH_STATUS = 'SET_REFRESH_STATUS';
export const GET_NEW_TOKEN_WITH_REFRESH = 'GET_NEW_TOKEN_WITH_REFRESH';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const CHANGE_USER_DATA = 'CHANGE_USER_DATA';

export const RESEND_CONFIRMATION_EMAIL = 'RESEND_CONFIRMATION_EMAIL';
export const SET_USER_LOGIN_DETAILS = 'SET_USER_LOGIN_DETAILS';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const RESEND_CONFIRMATION_EMAIL_FROM_TOKEN =
  'RESEND_CONFIRMATION_EMAIL_FROM_TOKEN';
export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
