export const REGISTER_FORM_SUBMIT = 'REGISTER_FORM_SUBMIT';
export const LOGIN_FORM_SUBMIT = 'LOGIN_FORM_SUBMIT';
export const CREATE_THREAD_FORM_SUBMIT = 'CREATE_THREAD_FORM_SUBMIT';
export const CREATE_THREAD_ANSWER_FORM_SUBMIT =
  'CREATE_THREAD_ANSWER_FORM_SUBMIT';
export const USER_EDIT_FORM_SUBMIT = 'USER_EDIT_FORM_SUBMIT';
export const SET_FORM_ERROR = 'SET_FORM_ERROR';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';

export const SET_INITIAL_FORM_DATA = 'SET_INITIAL_FORM_DATA';
export const RESET_FORM_DATA = 'RESET_FORM_DATA';
