export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CHANGE_CATEGORIES = 'CHANGE_CATEGORIES';

export const FETCH_LATEST_THREADS = 'FETCH_LATEST_THREADS';
export const CHANGE_LATEST_THREADS = 'CHANGE_LATEST_THREADS';

export const FETCH_THREADS_BY_CATEGORY = 'FETCH_THREADS_BY_CATEGORY';
export const CHANGE_CATEGORY_THREADS = 'CHANGE_CATEGORY_THREADS';

export const FETCH_THREAD_SINGLE = 'FETCH_THREAD_SINGLE';
export const SET_THREAD_SINGLE = 'SET_THREAD_SINGLE';

export const ADD_NEW_THREAD_MESSAGE = 'ADD_NEW_THREAD_MESSAGE';
export const CLEAR_THREAD_SINGLE = 'CLEAR_THREAD_SINGLE';

export const SEARCH_THREAD = 'SEARCH_THREAD';
export const CHANGE_SEARCH_THREAD_RESULT = 'CHANGE_SEARCH_THREAD_RESULT';
export const TOGGLE_THREAD_LOCK = 'TOGGLE_THREAD_LOCK';
